### ISSUE TITLE
int filesCount = 1; should be NSUInteger filesCount = 1;

### ISSUE THREAD

**Issue by rg5d** [CPLamb/RouteTracker#91]
int filesCount = 1; should be NSUInteger filesCount = 1; because 

filesCount = [self.directoryContent count]; 

causes a warning due the fact that self.directoryContent is a NSArray whose count method returns a NSUInteger.

https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSArray_Class/#//apple_ref/occ/instp/NSArray/count

Objective-C

@property(readonly) NSUInteger count

**Comment by CPLamb** [comment]
Done
